const quizAQuestions = [
    { question: "1. Why does Tom always get good grades?", translation: "¿Por qué Tom siempre saca buenas notas?", options: ["generous", "retired", "messy", "clever"], correct: 3 },
    { question: "2. What generates light?", translation: "¿Qué genera luz?", options: ["The moon.", "The sun.", "A mirror.", "A window."], correct: 1 },
    { question: "3. Did Mary display her photos?", translation: "¿Mostró Mary sus fotos?", options: ["cut", "buy", "see", "sell"], correct: 2 },
    { question: "4. Has Tom accepted the offer?", translation: "¿Ha aceptado Tom la oferta?", options: ["leasing", "protecting", "considering", "organizing"], correct: 2 },
    { question: "5. Can you turn on the lights?", translation: "¿Puedes encender las luces?", options: ["switch them on", "rely on them", "advertise in them", "fill them up"], correct: 0 },
    { question: "6. How many nations are in Africa?", translation: "¿Cuántas naciones hay en África?", options: ["machines", "countries", "forests", "people"], correct: 1 },
    { question: "7. I can't connect the fan to the outlet.", translation: "No puedo conectar el ventilador al tomacorriente.", options: ["cord", "court", "announcement", "advertisement"], correct: 0 },
    { question: "8. What do you think about his arguments?", translation: "¿Qué piensas de sus argumentos?", options: ["crowded", "frightened", "comfortable", "reasonable"], correct: 3 },
    { question: "9. Is the homework due today?", translation: "¿Vence hoy la tarea?", options: ["busy", "due", "powerful", "classified"], correct: 1 },
    { question: "10. Are you through with your meal?", translation: "¿Has terminado con tu comida?", options: ["worried", "married", "enlisted", "finished"], correct: 3 },
    { question: "11. What do they do at that factory?", translation: "¿Qué hacen en esa fábrica?", options: ["make", "buy", "fly", "repair"], correct: 0 },
    { question: "12. What is Mary's best characteristic?", translation: "¿Cuál es la mejor característica de Mary?", options: ["kind", "lost", "busy", "dull"], correct: 0 },
    { question: "13. Why did you exclude Tom from the game?", translation: "¿Por qué excluiste a Tom del juego?", options: ["he was the best player", "we needed more players", "he broke too many rules", "everyone wanted him to play"], correct: 2 },
    { question: "14. Do only U.S. students attend that school?", translation: "¿Solo estudiantes de EE. UU. asisten a esa escuela?", options: ["demanding", "international", "married", "official"], correct: 1 },
    { question: "15. Does Ms. Smith need help walking up the stairs?", translation: "¿Necesita la Sra. Smith ayuda para subir las escaleras?", options: ["generous", "disciplined", "hardworking", "elderly"], correct: 3 },
    { question: "16. Describe Tom's appearance.", translation: "Describe la apariencia de Tom.", options: ["smart and relaxed", "funny and quiet", "tall and thin", "calm and interesting"], correct: 2 },
    { question: "17. Does Mary work for the government?", translation: "¿Trabaja Mary para el gobierno?", options: ["collects taxes", "cleans houses", "sells clothing", "harvests crops"], correct: 0 },
    { word: "18. Does Mary have a new haircut?", translation: "¿Tiene Mary un nuevo corte de pelo?", options: ["powerful", "friendly", "reliable", "attractive"], correct: 3 },
    { question: "19. Does that appliance work?", translation: "¿Funciona ese aparato?", options: ["elevator", "screwdriver", "circuit", "lease"], correct: 2 },
    { question: "20. Is your job demanding?", translation: "¿Es tu trabajo exigente?", options: ["are on vacation", "have a lot of work", "take long breaks", "think it's easy"], correct: 1 },
    { question: "21. Can everyone use the swimming pool?", translation: "¿Puede todo el mundo usar la piscina?", options: ["available", "public", "private", "convenient"], correct: 1 },
    { question: "22. Does your building have good security?", translation: "¿Tiene tu edificio buena seguridad?", options: ["scary", "safe", "leaky", "freezing"], correct: 1 },
    { question: "23. When is retreat performed?", translation: "¿Cuándo se realiza la retirada?", options: ["It always occurs at the end of the duty day.", "Tom is tall, thin, blond, and wears glasses.", "They usually have a guard 12 hours per day.", "We'll move to the new house tomorrow, right?"], correct: 0 },
    { question: "24. How much is the rent?", translation: "¿Cuánto es el alquiler?", options: ["We honor the flag.", "It's $600 per month.", "She's only 25 years old.", "That's right, it's furnished."], correct: 1 },
    { question: "25. Who gets a ten percent discount?", translation: "¿Quién recibe un diez por ciento de descuento?", options: ["new cashiers", "store shoppers", "store personnel", "military personnel"], correct: 3 },
    { question: "26. You don't like meat, _______ you?", translation: "No te gusta la carne, ¿verdad?", options: ["are", "can", "have", "do"], correct: 3 },
    { question: "27. I can always _______ Mary when I need help.", translation: "Siempre puedo _______ Mary cuando necesito ayuda.", options: ["precede", "govern", "rely on", "argue with"], correct: 2 },
    { question: "28. Mary: Are you going to color your hair? Sarah: Yes, I'm going to _______.", translation: "Mary: ¿Te vas a teñir el pelo? Sarah: Sí, voy a _______.", options: ["color it brown", "it color brown", "it brown color", "color brown it"], correct: 0 },
    { question: "29. I don't like cake, and neither _______ she.", translation: "No me gusta el pastel, y a ella tampoco.", options: ["is", "likes", "does", "has"], correct: 2 },
    { question: "30. The lights went out. We need a _______.", translation: "Se fue la luz. Necesitamos una _______.", options: ["mirror", "candle", "newspaper", "television"], correct: 1 },
    { question: "31. I don't know how often _______.", translation: "No sé con qué frecuencia _______.", options: ["taught is this class", "is taught this class", "is this class taught", "this class is taught"], correct: 3 },
    { question: "32. Customer: I'd like to buy the newest book by John King. Book seller: I'm sorry. It's not _______ yet.", translation: "Cliente: Me gustaría comprar el libro más nuevo de John King. Vendedor: Lo siento. No está _______ todavía.", options: ["available", "official", "mandatory", "certain"], correct: 0 },
    { question: "33. Although we _______, we're best friends.", translation: "Aunque nosotros _______, somos mejores amigos.", options: ["talk a lot", "often fight", "grew up together", "like the same things"], correct: 1 },
    { question: "34. The teacher doesn't appear _______ well today.", translation: "El profesor no parece _______ bien hoy.", options: ["is", "be", "to be", "being"], correct: 2 },
    { question: "35. A marriage ceremony is a special _______.", translation: "Una ceremonia de matrimonio es una _______ especial.", options: ["occasion", "insignia", "demand", "quality"], correct: 0 },
    { question: "36. Closing the curtains _______ the room.", translation: "Cerrar las cortinas _______ la habitación.", options: ["dark", "darkly", "darker", "darkens"], correct: 3 },
    { question: "37. Your house will lose less heat if you _______ it.", translation: "Tu casa perderá menos calor si la _______.", options: ["insulate", "advertise", "power", "furnish"], correct: 0 },
    { question: "38. The baby's skin feels _______ silk.", translation: "La piel del bebé se siente _______ seda.", options: ["liked", "liking", "like", "like it"], correct: 2 },
    { question: "39. Everything that you need is in the box, _______ the instructions.", translation: "Todo lo que necesitas está en la caja, _______ las instrucciones.", options: ["from", "including", "through", "off"], correct: 1 },
    { question: "40. Captain Smith _______ to major yesterday.", translation: "El Capitán Smith _______ a mayor ayer.", options: ["promoted", "was promoting", "had promoted", "was promoted"], correct: 3 },
    { question: "41. I drive a _______ car.", translation: "Conduzco un coche de _______.", options: ["four-door", "four door", "four doors", "four-doors"], correct: 0 },
    { question: "42. Learning about _______ is an important part of basic training.", translation: "Aprender sobre _______ es una parte importante del entrenamiento básico.", options: ["real estate", "discipline", "advertisements", "vending machines"], correct: 1 },
    { question: "43. Do you know _______ open today?", translation: "¿Sabes si la biblioteca está abierta hoy?", options: ["is the library", "if is the library", "the library is", "if the library is"], correct: 3 },
    { question: "44. Teacher: Do you know where you should go in an emergency? Student: Yes, I know where _______.", translation: "Profesor: ¿Sabes a dónde debes ir en una emergencia? Estudiante: Sí, sé a dónde _______.", options: ["go", "goes", "to go", "should go"], correct: 3 },
    { question: "45. The cadets looked _______ in their new uniforms.", translation: "Los cadetes se veían _______ en sus nuevos uniformes.", options: ["elderly", "handsome", "dishonest", "stingy"], correct: 1 },
    { question: "46. Tom: What kind of transportation do you take? Mary: I use the _______.", translation: "Tom: ¿Qué tipo de transporte tomas? Mary: Uso el _______.", options: ["sofa", "library", "computer", "train"], correct: 3 },
    { question: "47. I swim well, and so _______ she.", translation: "Yo nado bien, y ella también.", options: ["does", "swims", "is", "has"], correct: 0 },
    { question: "48. My car will _______ next week.", translation: "Mi coche será _______ la próxima semana.", options: ["fix", "fixed", "be fixing", "be fixed"], correct: 3 },
    { question: "49. Does water boil at 100 degrees Celsius? Yes, _______.", translation: "¿Hierve el agua a 100 grados Celsius? Sí, _______.", options: ["face the flag", "that's correct", "she's a blonde", "the rent is due"], correct: 1 },
    { question: "50. Select the judgment.", translation: "Selecciona el juicio.", options: ["Does the rent include utilities?", "Face the direction of the flag.", "In my opinion, Mary drives too fast.", "Is it true that PT is at 0600 today?"], correct: 2 }
];