const quizBQuestions = [
    { question: "1. Which word means 'a person who repairs machines'?", translation: "¿Qué palabra significa 'una persona que repara máquinas'?", options: ["Operator", "Mechanic", "Pilot", "Cook"], correct: 1 },
    { question: "2. What is the opposite of 'complicated'?", translation: "¿Cuál es lo opuesto de 'complicado'?", options: ["Easy", "Difficult", "Complex", "Confusing"], correct: 0 },
    { question: "3. Select the correct word: The weather is very ________ today; it's raining heavily.", translation: "Selecciona la palabra correcta: El clima está muy ________ hoy; está lloviendo fuertemente.", options: ["Dry", "Humid", "Severe", "Warm"], correct: 2 },
    { question: "4. What does 'adjust' mean?", translation: "¿Qué significa 'adjust'?", options: ["To fix something permanently", "To change slightly for better performance", "To break down a machine", "To remove a part"], correct: 1 },
    { question: "5. The plane's ________ must be checked before takeoff.", translation: "El ________ del avión debe ser revisado antes del despegue.", options: ["Engine", "Recipe", "Calculator", "Ticket"], correct: 0 },
    { question: "6. Yes, he said that ________.", translation: "Sí, él dijo que ________.", options: ["his sister did it", "he didn't do it", "he was wrong", "nothing happened"], correct: 2 },
    { question: "7. Yes, it’s ________.", translation: "Sí, es ________.", options: ["demanding", "twisting", "running", "frightening"], correct: 0 },
    { question: "8. Yes, I ________ it for a year.", translation: "Sí, lo ________ por un año.", options: ["lost", "rented", "postponed", "canceled"], correct: 1 },
    { question: "9. Oh, they always ________.", translation: "Oh, ellos siempre ________.", options: ["lie", "share", "fly", "argue"], correct: 3 },
    { question: "10. He put a key in the ________.", translation: "Él puso una llave en la ________.", options: ["outlet", "door", "drawer", "closet"], correct: 1 },
    { question: "11. Because he's ________.", translation: "Porque él es ________.", options: ["handsome", "dishonest", "unfriendly", "cautious"], correct: 3 },
    { question: "12. Yes, I’m ________ it.", translation: "Sí, estoy ________ en ello.", options: ["thinking about", "guaranteeing", "destroying", "looking for"], correct: 0 },
    { question: "13. Yes, it’s ________.", translation: "Sí, es ________.", options: ["important", "expensive", "difficult", "finished"], correct: 1 },
    { question: "14. No, she ________.", translation: "No, ella ________.", options: ["went for a walk", "paid all her bills", "took a shower", "saw her friends"], correct: 1 },
    { question: "15. In the ________.", translation: "En la ________.", options: ["suitcase", "kitchen", "newspaper", "bathtub"], correct: 0 },
    { question: "16. Yes, he ________ all the time.", translation: "Sí, él ________ todo el tiempo.", options: ["does homework", "works outside", "watches TV", "helps his mother"], correct: 2 },
    { question: "17. Yes, he ________.", translation: "Sí, él ________.", options: ["missed it", "sang in it", "felt comfortable", "stayed at home"], correct: 3 },
    { question: "18. Yes, she's very ________.", translation: "Sí, ella es muy ________.", options: ["doubtful", "friendly", "irresponsible", "hardworking"], correct: 3 },
    { question: "19. ________ did.", translation: "________ lo hizo.", options: ["Tom", "Russia", "The soccer team", "The students"], correct: 0 },
    { question: "20. Sure, I can ________ them.", translation: "Claro, puedo ________ los.", options: ["connect", "cook", "shake", "locate"], correct: 3 },
    { question: "21. It'll be on ________.", translation: "Estará en ________.", options: ["Friday's test", "the report", "the table", "First Street"], correct: 2 },
    { question: "22. Yes, wear ________.", translation: "Sí, usa ________.", options: ["boots", "jeans", "a suit", "a T-shirt"], correct: 0 },
    { question: "23. Choose the correct option.", translation: "Elige la opción correcta.", options: ["They're outside public schools and on military bases.", "The US and French flags are red, white, and blue.", "Does the apartment building have a tennis court?", "There's a test tomorrow morning, isn't there?"], correct: 1 },
    { question: "24. Choose the correct option.", translation: "Elige la opción correcta.", options: ["When should we salute the flag?", "The store will close next week.", "It'll be available next week.", "We can have pets inside, can't we?"], correct: 0 },
    { question: "25. What kind of classes does the school offer?", translation: "¿Qué tipo de clases ofrece la escuela?", options: ["computers", "history and math", "music and acting", "health care"], correct: 0 },
    { question: "26. He doesn't look happy, ________ he?", translation: "Él no parece feliz, ¿verdad?", options: ["is", "will", "has", "does"], correct: 0 },
    { question: "27. Soldiers ________ the flag.", translation: "Los soldados ________ la bandera.", options: ["assign", "salute", "satisfy", "frighten"], correct: 1 },
    { question: "28. Your hands should ________ before every meal.", translation: "Tus manos deberían ________ antes de cada comida.", options: ["be washed", "be washing", "wash", "washed"], correct: 0 },
    { question: "29. The children are happy, and so ________ their parents.", translation: "Los niños están felices, y también sus padres.", options: ["do", "can", "are", "have"], correct: 2 },
    { question: "30. Andy got a perfect score. He got ________.", translation: "Andy obtuvo una puntuación perfecta. Obtuvo ________.", options: ["99%", "100%", "45%", "20%"], correct: 1 },
    { question: "31. It doesn't sound ________ a good plan.", translation: "No suena ________ un buen plan.", options: ["like it", "like", "liked", "liking"], correct: 1 },
    { question: "32. The rice has cooked long enough. Please ________ the stove.", translation: "El arroz se ha cocinado lo suficiente. Por favor ________ la estufa.", options: ["switch off", "turn on", "run", "power"], correct: 0 },
    { question: "33. The best cadets ________ for further training.", translation: "Los mejores cadetes ________ para entrenamiento adicional.", options: ["selected", "were selecting", "had selected", "were selected"], correct: 3 },
    { question: "34. Though Tom ________, he didn't go to the doctor.", translation: "Aunque Tom ________, no fue al médico.", options: ["felt wonderful", "lost his keys", "broke his leg", "ate healthy food"], correct: 2 },
    { question: "35. Andy is someone I can ________ during difficult times.", translation: "Andy es alguien en quien puedo ________ durante tiempos difíciles.", options: ["produce", "indicate", "rely on", "talk about"], correct: 2 },
    { question: "36. They own a ________ house.", translation: "Ellos son dueños de una casa de ________.", options: ["three-bedroom", "three bedroom", "three bedrooms", "three-bedrooms"], correct: 0 },
    { question: "37. Do you remember ________?", translation: "¿Recuerdas ________?", options: ["where the airport is", "where is the airport", "the airport is where", "the airport where is"], correct: 0 },
    { question: "38. The flow of ________ is extremely strong here.", translation: "El flujo de ________ es extremadamente fuerte aquí.", options: ["music", "water", "light", "fire"], correct: 1 },
    { question: "39. Mary: How do you like your tea? Andy: I ________.", translation: "Mary: ¿Cómo te gusta el té? Andy: Me ________.", options: ["like sweet it", "sweet it like", "sweet like it", "like it sweet"], correct: 3 },
    { question: "40. The toughest demand of my job is ________.", translation: "La exigencia más dura de mi trabajo es ________.", options: ["getting many awards", "taking long breaks", "working many hours", "going on vacation"], correct: 2 },
    { question: "41. I don't know ________ my ID card.", translation: "No sé ________ mi tarjeta de identificación.", options: ["whether I need", "whether do I need", "do I need", "I need"], correct: 0 }, // Wait, user marked D (I need) but "whether I need" is more natural. User marked D.
    { question: "42. Sue: Is this book due? Tom: Yes, you must ________ it.", translation: "Sue: ¿Vence este libro? Tom: Sí, debes ________ lo.", options: ["buy", "lend", "allow", "return"], correct: 3 },
    { question: "43. A ________ is an important official.", translation: "Un ________ es un oficial importante.", options: ["general", "musician", "mechanic", "driver"], correct: 0 },
    { question: "44. The animals seem ________ healthy.", translation: "Los animales parecen ________ sanos.", options: ["be", "are", "to be", "being"], correct: 2 },
    { question: "45. I need to buy some wire because I want to ________.", translation: "Necesito comprar algo de cable porque quiero ________.", options: ["make a cake", "fix the light", "write a letter", "sweep the floor"], correct: 1 },
    { question: "46. The butter will ________ if we take it out of the refrigerator.", translation: "La mantequilla se ________ si la sacamos del refrigerador.", options: ["softly", "soften", "softer", "soft"], correct: 1 },
    { question: "47. We didn't go to work, and neither ________ they.", translation: "No fuimos a trabajar, y ellos tampoco.", options: ["had", "went", "were", "did"], correct: 3 },
    { question: "48. Sue: Does he know what he can do to help? Tom: Yes, he knows what ________.", translation: "Sue: ¿Sabe él qué puede hacer para ayudar? Tom: Sí, sabe qué ________.", options: ["to do", "do", "does", "can do"], correct: 0 },
    { question: "49. Does the meeting start at 7:00 p.m.? Yes, ________.", translation: "¿Empieza la reunión a las 7:00 p.m.? Sí, ________.", options: ["your eyes are red and swollen", "the US flag precedes other flags", "our building has good security", "that's right, and come early"], correct: 3 },
    { question: "50. Select the judgment.", translation: "Selecciona el juicio.", options: ["How much are you asking for rent?", "Put your hand on your heart.", "Are you sure your information is correct?", "In my opinion, her haircut is awful."], correct: 3 }
];