const vocabularyList = [
    // 1. Personalidad y Apariencia Física
    { word: "Attractive", translation: "Atractivo/a", category: "Personalidad y Apariencia" },
    { word: "Honest", translation: "Honesto", category: "Personalidad y Apariencia" },
    { word: "Irresponsible", translation: "Irresponsable", category: "Personalidad y Apariencia" },
    { word: "Bald", translation: "Calvo", category: "Personalidad y Apariencia" },
    { word: "Beard", translation: "Barba", category: "Personalidad y Apariencia" },
    { word: "Blond / Blonde", translation: "Rubio/a", category: "Personalidad y Apariencia" },
    { word: "Brunet / Brunette", translation: "Moreno/a (pelo)", category: "Personalidad y Apariencia" },
    { word: "Mustache", translation: "Bigote", category: "Personalidad y Apariencia" },
    { word: "Clever", translation: "Listo / Inteligente", category: "Personalidad y Apariencia" },
    { word: "Neat", translation: "Limpio / Ordenado", category: "Personalidad y Apariencia" },
    { word: "Reliable", translation: "Confiable", category: "Personalidad y Apariencia" },
    { word: "Selfish", translation: "Egoísta", category: "Personalidad y Apariencia" },
    { word: "Stingy", translation: "Tacaño", category: "Personalidad y Apariencia" },
    { word: "Unselfish", translation: "Generoso / Altruista", category: "Personalidad y Apariencia" },
    { word: "Wavy", translation: "Ondulado", category: "Personalidad y Apariencia" },
    { word: "Friendly", translation: "Amigable", category: "Personalidad y Apariencia" },
    { word: "Generous", translation: "Generoso", category: "Personalidad y Apariencia" },
    { word: "Elderly", translation: "Anciano / Mayor", category: "Personalidad y Apariencia" },
    { word: "Handsome", translation: "Guapo", category: "Personalidad y Apariencia" },
    { word: "Hardworking", translation: "Trabajador", category: "Personalidad y Apariencia" },

    // 2. Vivienda y Servicios
    { word: "Advertise", translation: "Anunciar", category: "Vivienda y Servicios" },
    { word: "Appliance", translation: "Electrodoméstico", category: "Vivienda y Servicios" },
    { word: "Air conditioning", translation: "Aire acondicionado", category: "Vivienda y Servicios" },
    { word: "Available", translation: "Disponible", category: "Vivienda y Servicios" },
    { word: "Central", translation: "Central", category: "Vivienda y Servicios" },
    { word: "Dishwasher", translation: "Lavaplatos", category: "Vivienda y Servicios" },
    { word: "District", translation: "Distrito / Barrio", category: "Vivienda y Servicios" },
    { word: "Efficiency", translation: "Eficiencia / Monoambiente", category: "Vivienda y Servicios" },
    { word: "Furnished", translation: "Amueblado", category: "Vivienda y Servicios" },
    { word: "Garbage disposal", translation: "Triturador de basura", category: "Vivienda y Servicios" },
    { word: "Lease", translation: "Contrato de arrendamiento", category: "Vivienda y Servicios" },
    { word: "Heating", translation: "Calefacción", category: "Vivienda y Servicios" },
    { word: "Paint", translation: "Pintar / Pintura", category: "Vivienda y Servicios" },
    { word: "Privacy", translation: "Privacidad", category: "Vivienda y Servicios" },
    { word: "Public / Private", translation: "Público / Privado", category: "Vivienda y Servicios" },
    { word: "Real estate", translation: "Bienes raíces", category: "Vivienda y Servicios" },
    { word: "Utility", translation: "Servicio público", category: "Vivienda y Servicios" },
    { word: "Want ad", translation: "Anuncio clasificado", category: "Vivienda y Servicios" },

    // 3. Instituciones, Ciudadanía y Rangos Militares
    { word: "Anthem", translation: "Himno", category: "Instituciones y Militares" },
    { word: "Nation", translation: "Nación", category: "Instituciones y Militares" },
    { word: "Discipline", translation: "Disciplina", category: "Instituciones y Militares" },
    { word: "Official", translation: "Oficial / Funcionario", category: "Instituciones y Militares" },
    { word: "Display", translation: "Exhibir / Mostrar", category: "Instituciones y Militares" },
    { word: "Parade", translation: "Desfile", category: "Instituciones y Militares" },
    { word: "Gathering", translation: "Reunión", category: "Instituciones y Militares" },
    { word: "Position", translation: "Posición / Cargo", category: "Instituciones y Militares" },
    { word: "Government", translation: "Gobierno", category: "Instituciones y Militares" },
    { word: "Symbol", translation: "Símbolo", category: "Instituciones y Militares" },
    { word: "International", translation: "Internacional", category: "Instituciones y Militares" },
    { word: "Uniform", translation: "Uniforme", category: "Instituciones y Militares" },
    { word: "Mandatory", translation: "Obligatorio", category: "Instituciones y Militares" },
    { word: "Sergeant", translation: "Sargento", category: "Instituciones y Militares" },
    { word: "Warrant officer", translation: "Oficial técnico", category: "Instituciones y Militares" },

    // 4. Electricidad y Herramientas
    { word: "Attach", translation: "Adjuntar / Unir", category: "Electricidad y Herramientas" },
    { word: "Insulated", translation: "Aislado", category: "Electricidad y Herramientas" },
    { word: "Charge", translation: "Carga / Cargar", category: "Electricidad y Herramientas" },
    { word: "Live wire", translation: "Cable con corriente", category: "Electricidad y Herramientas" },
    { word: "Circuit", translation: "Circuito", category: "Electricidad y Herramientas" },
    { word: "Powerful", translation: "Potente", category: "Electricidad y Herramientas" },
    { word: "Conductor", translation: "Conductor", category: "Electricidad y Herramientas" },
    { word: "Screw", translation: "Tornillo", category: "Electricidad y Herramientas" },
    { word: "Copper", translation: "Cobre", category: "Electricidad y Herramientas" },
    { word: "Screwdriver", translation: "Destornillador", category: "Electricidad y Herramientas" },
    { word: "Current", translation: "Corriente", category: "Electricidad y Herramientas" },
    { word: "Shock", translation: "Descarga / Choque", category: "Electricidad y Herramientas" },
    { word: "Electrician", translation: "Electricista", category: "Electricidad y Herramientas" },
    { word: "Solder", translation: "Soldar", category: "Electricidad y Herramientas" },
    { word: "Flow", translation: "Flujo / Fluir", category: "Electricidad y Herramientas" },
    { word: "Switch", translation: "Interruptor", category: "Electricidad y Herramientas" },
    { word: "Generate", translation: "Generar", category: "Electricidad y Herramientas" },
    { word: "Wire / Wiring", translation: "Cable / Cableado", category: "Electricidad y Herramientas" },

    // Verbos Comunes
    { word: "Demand", translation: "Demandar / Exigir", category: "Verbos Comunes" },
    { word: "Deny", translation: "Negar", category: "Verbos Comunes" },
    { word: "Depend on", translation: "Depender de", category: "Verbos Comunes" },
    { word: "Rely on", translation: "Confiar en / Contar con", category: "Verbos Comunes" },
    { word: "Scream", translation: "Gritar", category: "Verbos Comunes" },
    { word: "Trust", translation: "Confiar", category: "Verbos Comunes" },
    { word: "Argue", translation: "Discutir / Argüir", category: "Verbos Comunes" },
    { word: "Consider", translation: "Considerar", category: "Verbos Comunes" },
    { word: "Exclude / Include", translation: "Excluir / Incluir", category: "Verbos Comunes" },
    { word: "Participate", translation: "Participar", category: "Verbos Comunes" }
];