const vocabularyList = [
    // Lesson 1: Meet My Sister-in-Law
    { word: "Attract", translation: "Atraer", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Divorce", translation: "Divorcio / Divorciarse", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "End up", translation: "Terminar / Acabar (en una situación o lugar)", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Get along (in)", translation: "Progresar / Desenvolverse (en)", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Get along (with)", translation: "Llevarse bien (con alguien)", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Inquire (about)", translation: "Preguntar / Averiguar / Pedir información (sobre)", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Neglect (to)", translation: "Descuidar / Dejar de hacer algo", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Put up with", translation: "Tolerar / Aguantar / Soportar", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Tolerate", translation: "Tolerar", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "All at once", translation: "De repente / Todo a la vez", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Once in a while", translation: "De vez en cuando", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Along with", translation: "Junto con / Además de", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Alongside (of)", translation: "Al lado de / Junto a", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Complete", translation: "Completo / Completar", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Consequently", translation: "Por consiguiente / Por lo tanto", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Eager", translation: "Entusiasta / Ansioso / Deseoso", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "General", translation: "General", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "In addition", translation: "Además / Adicionalmente", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Incomplete", translation: "Incompleto", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Specific", translation: "Específico", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Tolerant", translation: "Tolerante", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Female", translation: "Femenino / Hembra", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Grandchild / Children", translation: "Nieto(s)", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Granddaughter", translation: "Nieta", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Grandson", translation: "Nieto", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "In-law", translation: "Pariente político (por matrimonio)", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Knowledge", translation: "Conocimiento", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Male", translation: "Masculino / Varón", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Relationship", translation: "Relación / Parentesco", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Spouse", translation: "Cónyuge / Esposo(a)", category: "Lección 1 - Meet My Sister-in-Law" },
    { word: "Tolerance", translation: "Tolerancia", category: "Lección 1 - Meet My Sister-in-Law" },

    // Lesson 2: Was It Preventable?
    { word: "Arrange", translation: "Organizar / Arreglar / Coordinar", category: "Lección 2 - Was It Preventable?" },
    { word: "Assist", translation: "Ayudar / Asistir", category: "Lección 2 - Was It Preventable?" },
    { word: "Bite / bit / bitten", translation: "Morder / Picar (insecto)", category: "Lección 2 - Was It Preventable?" },
    { word: "Could have", translation: "Podría haber / Pudo haber", category: "Lección 2 - Was It Preventable?" },
    { word: "Couldn't have", translation: "No podría haber / No pudo haber", category: "Lección 2 - Was It Preventable?" },
    { word: "Drop off", translation: "Dejar / Entregar (a alguien o algo en un lugar)", category: "Lección 2 - Was It Preventable?" },
    { word: "Drown", translation: "Ahogarse (en agua)", category: "Lección 2 - Was It Preventable?" },
    { word: "Insist (on)", translation: "Insistir (en)", category: "Lección 2 - Was It Preventable?" },
    { word: "Keep away (from)", translation: "Mantenerse alejado (de)", category: "Lección 2 - Was It Preventable?" },
    { word: "Kill", translation: "Matar", category: "Lección 2 - Was It Preventable?" },
    { word: "Misplace", translation: "Extraviar / Perder de vista", category: "Lección 2 - Was It Preventable?" },
    { word: "Prevent", translation: "Prevenir / Evitar", category: "Lección 2 - Was It Preventable?" },
    { word: "Run across", translation: "Encontrarse con por casualidad / Cruzar corriendo", category: "Lección 2 - Was It Preventable?" },
    { word: "Stay away (from)", translation: "Permanecer alejado (de)", category: "Lección 2 - Was It Preventable?" },
    { word: "Use up", translation: "Consumir por completo / Agotar", category: "Lección 2 - Was It Preventable?" },
    { word: "According to", translation: "Según / De acuerdo con", category: "Lección 2 - Was It Preventable?" },
    { word: "At least", translation: "Por lo menos / Al menos", category: "Lección 2 - Was It Preventable?" },
    { word: "Convincing", translation: "Convincente", category: "Lección 2 - Was It Preventable?" },
    { word: "Entire", translation: "Entero / Completo / Todo", category: "Lección 2 - Was It Preventable?" },
    { word: "Fatal", translation: "Fatal / Mortal", category: "Lección 2 - Was It Preventable?" },
    { word: "Otherwise", translation: "De lo contrario / De otra manera", category: "Lección 2 - Was It Preventable?" },
    { word: "Preventable", translation: "Prevenible / Evitable", category: "Lección 2 - Was It Preventable?" },
    { word: "Fuel", translation: "Combustible", category: "Lección 2 - Was It Preventable?" },

    // Lesson 3: NCO Academies
    { word: "Accomplish", translation: "Lograr / Cumplir / Llevar a cabo", category: "Lección 3 - NCO Academies" },
    { word: "Account for", translation: "Explicar / Justificar / Rendir cuentas", category: "Lección 3 - NCO Academies" },
    { word: "Achieve", translation: "Alcanzar / Lograr / Conseguir", category: "Lección 3 - NCO Academies" },
    { word: "Adjust to", translation: "Adaptarse a / Ajustarse a", category: "Lección 3 - NCO Academies" },
    { word: "Communicate", translation: "Comunicarse", category: "Lección 3 - NCO Academies" },
    { word: "Congratulate", translation: "Felicitar", category: "Lección 3 - NCO Academies" },
    { word: "Develop", translation: "Desarrollar", category: "Lección 3 - NCO Academies" },
    { word: "Guide", translation: "Guiar / Guía", category: "Lección 3 - NCO Academies" },
    { word: "Make sense", translation: "Tener sentido / Ser lógico", category: "Lección 3 - NCO Academies" },
    { word: "Object (to)", translation: "Oponerse (a) / Objetar", category: "Lección 3 - NCO Academies" },
    { word: "Obtain", translation: "Obtener / Conseguir", category: "Lección 3 - NCO Academies" },
    { word: "Succeed", translation: "Tener éxito / Triunfar", category: "Lección 3 - NCO Academies" },
    { word: "Confident", translation: "Seguro de sí mismo / Confiado", category: "Lección 3 - NCO Academies" },
    { word: "Educational", translation: "Educativo", category: "Lección 3 - NCO Academies" },
    { word: "Routine", translation: "Rutina / Rutinario", category: "Lección 3 - NCO Academies" },
    { word: "Sensible", translation: "Sensato / Prudente / Lógico", category: "Lección 3 - NCO Academies" },
    { word: "Someday", translation: "Algún día", category: "Lección 3 - NCO Academies" },
    { word: "Successful", translation: "Exitoso / Próspero", category: "Lección 3 - NCO Academies" },
    { word: "Capability", translation: "Capacidad / Aptitud", category: "Lección 3 - NCO Academies" },
    { word: "Guidance", translation: "Orientación / Guía / Asesoramiento", category: "Lección 3 - NCO Academies" },
    { word: "Method", translation: "Método", category: "Lección 3 - NCO Academies" },
    { word: "Mission", translation: "Misión", category: "Lección 3 - NCO Academies" },
    { word: "Skill", translation: "Habilidad / Destreza", category: "Lección 3 - NCO Academies" },
    { word: "Success", translation: "Éxito", category: "Lección 3 - NCO Academies" },
    { word: "Technique", translation: "Técnica", category: "Lección 3 - NCO Academies" },

    // Lesson 4: Learning a Lesson
    { word: "Annoy", translation: "Molestar / Fastidiar", category: "Lección 4 - Learning a Lesson" },
    { word: "Disappoint", translation: "Decepcionar / Desilusionar", category: "Lección 4 - Learning a Lesson" },
    { word: "Drop out of", translation: "Abandonar / Retirarse de (la escuela, un curso)", category: "Lección 4 - Learning a Lesson" },
    { word: "Hand in", translation: "Entregar (una tarea, informe, etc.)", category: "Lección 4 - Learning a Lesson" },
    { word: "Lack", translation: "Carecer de / Faltar", category: "Lección 4 - Learning a Lesson" },
    { word: "Put aside", translation: "Dejar a un lado / Ahorrar", category: "Lección 4 - Learning a Lesson" },
    { word: "Regret", translation: "Lamentar / Arrepentirse", category: "Lección 4 - Learning a Lesson" },
    { word: "Rush", translation: "Apresurarse / Prisa", category: "Lección 4 - Learning a Lesson" },
    { word: "Start out (on)", translation: "Comenzar / Emprender (un viaje o actividad)", category: "Lección 4 - Learning a Lesson" },
    { word: "Stay up", translation: "Quedarse despierto / Desvelarse", category: "Lección 4 - Learning a Lesson" },
    { word: "Take off", translation: "Quitarse (ropa) / Despegar (avión) / Tomarse libre (tiempo)", category: "Lección 4 - Learning a Lesson" },
    { word: "Turn in", translation: "Entregar / Acostarse a dormir", category: "Lección 4 - Learning a Lesson" },
    { word: "Volunteer", translation: "Ofrecerse como voluntario / Voluntario", category: "Lección 4 - Learning a Lesson" },
    { word: "Waste", translation: "Desperdiciar / Malgastar / Desecho", category: "Lección 4 - Learning a Lesson" },
    { word: "Annoyed", translation: "Molesto / Enfadado", category: "Lección 4 - Learning a Lesson" },
    { word: "Annoying", translation: "Molesto / Fastidioso / Irritante", category: "Lección 4 - Learning a Lesson" },
    { word: "Disappointed", translation: "Decepcionado / Desilusionado", category: "Lección 4 - Learning a Lesson" },
    { word: "Disappointing", translation: "Decepcionante / Desilusionante", category: "Lección 4 - Learning a Lesson" },
    { word: "Guilty", translation: "Culpable", category: "Lección 4 - Learning a Lesson" },
    { word: "Helpful", translation: "Servicial / Útil / De ayuda", category: "Lección 4 - Learning a Lesson" },
    { word: "Lenient", translation: "Indulgente / Permisivo / Poco estricto", category: "Lección 4 - Learning a Lesson" },
    { word: "Strict", translation: "Estricto / Riguroso", category: "Lección 4 - Learning a Lesson" },
    { word: "Attention", translation: "Atención", category: "Lección 4 - Learning a Lesson" },
    { word: "Helmet", translation: "Casco", category: "Lección 4 - Learning a Lesson" },
    { word: "In a rush", translation: "Con prisa / Apurado", category: "Lección 4 - Learning a Lesson" },
    { word: "Learn a lesson", translation: "Aprender una lección", category: "Lección 4 - Learning a Lesson" },
    { word: "Lose one's temper", translation: "Perder los estribos / Perder la paciencia", category: "Lección 4 - Learning a Lesson" },
    { word: "Pay attention to", translation: "Prestar atención a", category: "Lección 4 - Learning a Lesson" }
];
